Initial push for creating a PyPi library
Ask-Iggy-Inc/iggy-api-python pull request #1
Opened 2021-02-17 16:23 UTC by zhaovan

Initial code for creating a python library. Has testing from pytest.

Solves: https://linear.app/askiggy/issue/IGGY-602/iggy-api-python-module

2021-02-17 17:09 UTC, bdejesus requested changes
Can we name this library `iggy-api-python` or `iggyapi` (or the equivalent Python naming format)? I've been using the pattern `iggy-[project]-[language/framework]` and it would make findability a little easier when there's a recognizable pattern.

Otherwise, just a few minor comments.

2021-02-17 17:09 UTC, bdejesus commented on README.md
> +import api from iggypythonlib
I think this is supposed to be 
```python
from iggypythonlib import api
```

2021-02-17 17:09 UTC, bdejesus commented on README.md
> +myapi = api.IggyAPI("<your_token_here")
nitpick - missing closing bracket around `your_token_here`

2021-02-17 17:12 UTC, bdejesus commented
Now that we have more than one library that tests against the API responses, it might be a good idea to start looking into using the oas file in the backend/gateway project (https://github.com/Ask-Iggy-Inc/backend/blob/main/services/gateway/app/open-api.yaml) as a source of truth for testing instead of having to mock these for every library.

2021-02-18 14:44 UTC, acocos reviewed
This looks awesome @zhaovan !

Similar to Ben I want to make sure we're being consistent in naming -- both among the various components of this library (repo name, pip package name, module base dir) and for the API calls themselves (e.g. `api.ENDPOINT` would be the same as the actual `ENDPOINT`).

Some ideas for follow-on:
- turning `options` dict into a class so that we can provide helpful validation and type checking messages
- adding a method that turns any geometry output into a shapely object, or a list of geometries into a geopandas geodataframe

2021-02-18 14:44 UTC, acocos commented on README.md
> +# @ask-iggy/iggypythonlib
In line with @bdejesus 's comment about the name of this library, I think it would be great if we could keep consistency between the repo name (`iggypythonlib` --> `$NAME`), the pip package name (`iggy-python` --> `$NAME`) and the module name itself (`iggypythonlib/api.py` --> `$NAME/api.py`). The `$NAME` can be `iggy-python-api` or `iggyapi`, whichever folks like better.

2021-02-18 14:44 UTC, acocos commented on iggypythonlib/api.py
> +    def poi(self, options, body={}):
Minor nitpick - could this be `points_of_interest` to keep it the same as the API call? Same with `points_of_interest_options` and `amenities_score`?

2021-02-19 00:38 UTC, Zack-walker reviewed
lgtm

2021-02-19 00:56 UTC, lindsay-pettingill reviewed
as far as i can tell, this makes the process of hitting the API dead simple, but what happens once the object is returned? is there anything we can add to this that helps out with any downstream tasks?
examples: plot clusters or isochrones on a map, put data in a dataframe, export data to csv, snowflake, etc? i think @acocos or @TankofVines may have some thoughts here, too

2021-02-22 21:09 UTC, merged